### ISSUE TITLE
Don't stop scanning when a barcode is found SINGLE_AUTO

### ISSUE THREAD

**Issue by daniel-stoneuk** [Credntia/MVBarcodeReader#21]
I'd like to validate the scanned barcode to see if it's data adheres to a specific format - if not, continue scanning. Currently the fragment stops scanning.

Please may you either 
a) add a method to restart the camera preview
b) don't stop the camera preview

Thanks,
Dan

**Comment by iamMehedi** [comment]
just calling `initiateCamera()` when you need to start scanning again should work. It's a `protected` method but you can easily access it by extending the fragment or via reflection.
