### ISSUE TITLE
Tap not detected on SINGLE_MANUAL

### ISSUE THREAD

**Issue by samurake** [Credntia/MVBarcodeReader#25]
Hi, on SINGLE_MANUAL mode, when multiple barcodes are detected, they are highlighted on screen, but when tapping on one of them, nothing happens. Sometimes the selection action is triggered if tapping randomly near the highlighted areas and one of the codes is selected. 

Do you know something about this issue? I need help as quick as possible.

Thanks.

**Comment by iamMehedi** [comment]
@samurake You need to tap inside the highlighted box to select that barcode. The barcode detection is a continuous process and the highlighted boxes are updated after processing each frame from camera. The tap might do nothing in case if the box just moved as soon as you tapped and the point of tap is no longer inside the box. This should be a rare case though.

**Comment by samurake** [comment]
I am tapping inside the highlighted box, but nothing happens. I cloned your sample app code to see if the bug is in my app or the library itself and I made a screen recording so you can see it's behavior.
https://drive.google.com/open?id=0B-ZbHNmWeq_QVThVME5ldmJKUWM
Can you help me with a fix as soon as possible?

**Comment by samurake** [comment]
As I said before, sometimes it randomly works, but that rarely happens. Maybe there's a memory leak on the touch listeners for the highlighted areas...

**Comment by iamMehedi** [comment]
@samurake the scan with dialog is a test setup for testing #15, that setup is not recommended.

**Comment by samurake** [comment]
So you can't fix it ?

**Comment by iamMehedi** [comment]
@samurake pull the `develop` branch and test. The issue should be resolved.
