### ISSUE TITLE
Can not import sample "MVBarcodeReader-master" into Android Studio and start it

### ISSUE THREAD

**Issue by forenbuddy** [Credntia/MVBarcodeReader#28]
I am trying to import the sample, but it won't show the module "app" and so I cannot start and test it. 

When I import the sample via "File->New->Import Project", after all loading is finished, then in the Android tab of the Project, there is no "app", but only the "Gradle Scripts", although I see the "app" folder in the "Project Files" tab. I also can not import it then (File->New->Import Module), because it says it already exists.

Under "Project Structure"->Modules it does not show "app" but "MVBarcodeReader-master". I can not add "app", as it then states: "Project already contains module with this name". This module "MVBarcodeReader-master" does not have any "Properties", "Signing", "Flavors", "Build Types" tabs, but only the "Dependencies" tab and so I can not build or start the sample. 

I searched for the past days to find a solution to this or some clarification to the underlying problem, but could not find any. All similar problems solutions on stackoverflow.com and the like, that I can find, did not yield any progress. I am stuck here.

Any ideas, what could go wrong or how I can proceed next to solve this problem?

Please help!

**Comment by iamMehedi** [comment]
@forenbuddy Just clone the repo with git and then select "Open An Existing Android Studio Project" from the Android Studio welcome screen and choose the project.
<img width="651" alt="screen shot 2017-09-15 at 5 26 26 pm" src="https://user-images.githubusercontent.com/3691635/30480489-d4cd43ec-9a3b-11e7-81ba-a6877730a354.png">

Everything should be just fine (tried this just now)
<img width="790" alt="screen shot 2017-09-15 at 5 27 54 pm" src="https://user-images.githubusercontent.com/3691635/30480520-f22cb7a6-9a3b-11e7-90d9-374e54d4dbfc.png">
