### ISSUE TITLE
Scanner Activity Questions

### ISSUE THREAD

**Issue by annttiigs** [Credntia/MVBarcodeReader#30]
two questions here;

1. Should I override the activity onCreate to load another layout instead of it's default ?
or is there a way to configure it ? 
2. How can I slowdown the activity shutdown once the barcode found ? (beside overriding)

**Comment by iamMehedi** [comment]
1. If you want a different layout you can create your own and embed the `BarcodeCaptureFragment` in it. No need to extend the scanner Activity. 
2. There isn't a way without extending the scanner activity or `BarcodeCaptureFragment`
